### ISSUE TITLE
pausar video quando passar para a proximo video

### ISSUE THREAD

**Issue by enieber** [psantunes/bolsonaro_quiz_game#1]
Quando você aperta play nos videos e responde verdadeiro ou falso o video continua tocando

**Comment by psantunes** [comment]
Bug foi corrigido. Foi usada o comando v-if para interromper a execução dos vídeos.

No lugar surgiu um novo pequeno bug no resultado do quiz - o Vue não consegue renderizar novamente o tweet do presidente usado na terceira questão. Mas o texto do tweet está lá, de forma que não prejudica a compreensão das respostas do quiz.
